//======================================================
// HIENLUONG - LANGUAGE
//======================================================

const LANGUAGES={
    vi:{
        "header.subtitle":"Quê hương tôi",
        "marquee":"❤️ Chào mừng bạn đến với Website Hiền Lương • Lưu giữ ký ức quê hương • Kết nối những người con Hiền Lương trên mọi miền đất nước ❤️",
        "nav.home":"Trang chủ",
        "nav.menu":"Menu",
        "nav.community":"Cộng đồng",
        "nav.hangkinh":"Hàng kỉnh",
        "nav.explore":"Khám phá",
        "nav.fund":"Quỹ làng",
        "nav.personal":"Cá nhân",
"explore.title":"KHÁM PHÁ",
"explore.subtitle":"Quê hương Hiền Lương",
"explore.intro":"Giới thiệu",
"explore.history":"Lịch sử",
"explore.famous":"Danh nhân",
"explore.tourism":"Điểm du lịch",
"explore.craft":"Sản vật làng nghề",
"explore.landmark":"Địa danh lịch sử",
"explore.clan":"Họ tộc",
"explore.documents":"Tư liệu",
"explore.notice":"Thông báo",
"community.title":"KẾT NỐI",
"community.subtitle":"Cộng đồng Hiền Lương",
"community.news":"Tin hàng ngày",
"community.articles":"Thư viện bài viết",
"community.members":"Danh sách thành viên",
"community.finance":"Tài chính",
"personal.title":"TÀI KHOẢN",
"personal.subtitle":"cá nhân",
"personal.login":"Đăng nhập",
"personal.register":"Đăng ký",
"hero.title":"Khám phá quê hương",
"hero.heading":"Gia Truyền",
"hero.years":"500 Năm",
"hero.heading2":"Ngọn Lửa Hồng Bên Sông Bồ",
"hero.description":"Những câu chuyện, ký ức, con người và giá trị văn hóa được lưu giữ qua từng chuyên mục.",
"culture.title":"QUÊ HƯƠNG",
"culture.heading":"Lịch sử & Văn hóa",
"culture.intro":"Giới thiệu",
"culture.introDesc":"Khám phá quê hương Hiền Lương.",
"culture.history":"Lịch sử - Tế tự",
"culture.historyDesc":"Những dấu mốc và ký ức quê hương.",
"culture.famous":"Danh nhân",
"culture.famousDesc":"Những người con tiêu biểu của quê hương.",
"culture.tourism":"Điểm du lịch",
"culture.tourismDesc":"Những cảnh đẹp và điểm đến của quê hương.",
"culture.craft":"Sản vật làng nghề",
"culture.craftDesc":"Những sản vật và nét đặc trưng của làng nghề.",
"culture.landmark":"Địa danh lịch sử",
"culture.landmarkDesc":"Những địa danh gắn với lịch sử quê hương.",
"culture.clan":"Họ tộc",
"culture.clanDesc":"Các dòng họ và gia phả của quê hương.",
"culture.documents":"Tư liệu",
"culture.documentsDesc":"Những tư liệu quý về quê hương Hiền Lương.",
"culture.notice":"Thông Báo",
"culture.noticeDesc":"Thông báo của quê hương Hiền Lương.",
"communityCards.title":"CỘNG ĐỒNG",
"communityCards.heading":"Kết nối người Hiền Lương",
"communityCards.news":"Tin hàng ngày",
"communityCards.newsDesc":"Cập nhật những câu chuyện và tin tức.",
"communityCards.articles":"Thư viện bài viết",
"communityCards.articlesDesc":"Nơi chia sẻ những câu chuyện riêng.",
"communityCards.members":"Danh sách thành viên",
"communityCards.membersDesc":"Cộng đồng những người con Hiền Lương.",
"communityCards.finance":"Tài chính",
"communityCards.financeDesc":"Thông tin tài chính của cộng đồng.",
"hangkinh.title":"HÀNG KỈNH",
"hangkinh.heading":"Kết nối đồng hương & phường thợ",
"hangkinh.motto":"18 Hàng Kỉnh: \"Ly Hương Bất Ly Tổ\"",
"hangkinh.intro":"Tổ chức phường nghề độc đáo của người thợ rèn Hiền Lương gắn kết các chi hội từ Đông Hà, Quảng Trị, Câu Nhi, Huế, Đà Nẵng đến TP.HCM và kiều bào hải ngoại.",
"hangkinh.listTitle":"Danh Bộ 18 Chi Hội Hàng Kỉnh Lịch Sử (TS. Bùi Thị Tân, 1996):",
"hangkinh.loading":"Đang tải danh sách Hàng Kỉnh...",
"tientho.label":"VINH DANH TIỀN TỔ",
"tientho.title":"Danh Sách Các Vị Tiền Hiền Thủy Tổ",
"tientho.description":"Những bậc tiền nhân đặt nền móng lập làng Hoa Lang năm 1445.",
"tientho.loading":"⏳ Đang tải danh sách Tiền Hiền...",
"thuocphim.label":"KÝ ỨC QUÊ HƯƠNG",
"thuocphim.title":"Các Thước Phim Quý Làng Hiền Lương",
"thuocphim.description":"Những hình ảnh và thước phim lưu giữ ký ức, con người và những câu chuyện thân thương của quê hương Hiền Lương.",
"thuocphim.screenTitle":"THƯỚC PHIM HIỀN LƯƠNG",
"thuocphim.screenHint":"Chọn một thước phim bên dưới",
"thuocphim.loading":"⏳ Đang tải danh sách thước phim...",
"tuhao.label":"TỰ HÀO QUÊ HƯƠNG",
"tuhao.title":"10+ Tuyến Phố Tại Huế Vinh Danh Làng Rèn Hiền Lương",
"tuhao.street1":"Đường Hoàng Văn Lịch",
"tuhao.desc1":"Cảng Bãi Dâu, TP. Huế • Kỹ sư cơ khí đầu tiên đóng tàu hơi nước",
"tuhao.street2":"Đường Nguyễn Lương Nhàn",
"tuhao.desc2":"Nối TL11C và TL9 (Phong Thái) • Bình Thắng Nam, Chưởng phủ sự",
"tuhao.street3":"Đường Trương Như Cương",
"tuhao.desc3":"Khu đô thị mới Huế • Phụ chính đại thần Hiền Lương Hầu",
"tuhao.street4":"Đường Trần Đình Bá",
"tuhao.desc4":"Trung tâm TP. Huế • Phó bảng Thượng thư Bộ Hình, Bộ Binh",
"tuhao.street5":"Đường Trần Văn Đắc",
"tuhao.desc5":"Phường Phong Thái • Chánh thất phẩm Súng Tượng cục triều Nguyễn",
"tuhao.street6":"Đường Hoa Lang & Triều Dương",
"tuhao.desc6":"Phường Phong Thái • Vinh danh tên lập làng 1445 và 6 phường đồi",
"disan.label":"DI SẢN QUÊ HƯƠNG",
"disan.title":"Di Sản Làng Nghề Truyền Thống",
"disan.subtitle":"Ba Mạch Nguồn Nuôi Sống Làng Quê Bên Sông Bồ",
"disan.description":"Nghề rèn sắt truyền đời kết hợp cùng hương thơm dầu đậu phụng nguyên chất và sắc tím nương dâu tạo nên nét văn hóa kinh tế trù phú, đặc sắc của quê hương.",
"disan.ren.title":"Lửa Rèn Trăm Năm",
"disan.ren.description":"Kỹ thuật \"cháy dao cháy rựa\" kẹp lõi thép tốt giữa hai thanh sắt non, tôi qua nước muối bột sừng trâu chém đá không mẻ. Đóng góp chế tạo vũ khí cho triều đình và ba tàu hơi nước Yên Phi, Vân Phi, Vũ Phi.",
"disan.ren.quote":"\"Lưỡng diệt hoàng sa, ông tướng đại ca tay cầm thiết thù...\"",
"disan.dauphung.title":"Dầu Đậu Phụng Ép Thủ Công",
"disan.dauphung.description":"Hạt lạc sẻ giống bản địa được chọn lọc kỹ càng, xay bột, hấp nhiệt và ép nén bằng cối gỗ truyền thống. Từng giọt dầu vàng óng, thơm nức gian bếp quê, nguyên chất 100% không pha tạp.",
"disan.dauphung.quote":"Hương vị thân thương trong từng mâm cơm của bà con xứ Huế.",
"disan.dau.title":"Nương Dâu Hái Trái Ven Sông",
"disan.dau.description":"Dâu tằm tại Hiền Lương thuần trồng lấy trái chín mọng ngâm đường phèn giải nhiệt những trưa hè oi ả, hoàn toàn không có nghề ươm tơ dệt lụa. Món quà dân dã thanh tao của đồng quê.",
"disan.dau.quote":"Thức uống thảo mộc dân dã gắn liền ký ức tuổi thơ.",
"guibai.label":"BAN BIÊN TẬP HIỀN LƯƠNG",
"guibai.title":"Gửi Bài Viết Hoặc Kỷ Vật Cho Ban Biên Tập",
"guibai.description":"Hãy gửi những câu chuyện, hình ảnh và tư liệu quý để cùng lưu giữ ký ức quê hương Hiền Lương.",
"guibai.author":"Họ và tên tác giả / Người gửi",
"guibai.phone":"Số điện thoại / Zalo",
"guibai.branch":"Chi hội Hàng Kỉnh / Nơi ở",
"guibai.content":"Tóm tắt nội dung bài viết hoặc tư liệu đóng góp",
"guibai.submit":"Gửi Thông Tin Cho Ban Biên Tập",
"footer.title":"LÀNG RÈN HIỀN LƯƠNG",
"footer.about":"Lưu giữ di sản văn hóa phi vật thể cố đô Huế. Nơi hội tụ tinh hoa làng nghề rèn kim khí hơn 500 năm lịch sử.",
"footer.contact":"Thông Tin Liên Hệ",
"footer.address":"Xã Phong Hiền, Huyện Phong Điền, Tỉnh Thừa Thiên Huế",
"footer.hotline":"Hotline: 098x xxx xxx (Ban biên tập)",
"footer.map":"Vị Trí Trên Bản Đồ",
"footer.distance":"Cách trung tâm TP. Huế khoảng 25km về phía Bắc.",
"footer.mapLink":"Mở Google Maps Chỉ Đường",
"footer.version":"Website Version 2.0.0",
"footer.written":"Written by : Trương Văn Thành",
"footer.admin":"Đăng nhập quản trị",
"footer.copyright":"© 2026 HIỀN LƯƠNG. All Rights Reserved.",
"mobile.home":"Trang chủ",
"mobile.category":"Danh mục",
"mobile.community":"Cộng đồng",
"mobile.personal":"Cá nhân",
"mobileCategory.title":"📚 DANH MỤC",
"mobileCategory.intro":"📘 Giới thiệu",
"mobileCategory.history":"📜 Lịch sử",
"mobileCategory.famous":"👤 Danh Nhân",
"mobileCategory.tourism":"🏞 Điểm du lịch",
"mobileCategory.craft":"🍲 Sản vật làng nghề",
"mobileCategory.landmark":"📍 Địa danh lịch sử",
"mobileCategory.clan":"👪 Họ tộc",
"mobileCategory.documents":"📚 Tư liệu",
"mobileCategory.notice":"📢 Thông Báo",
"mobileCommunity.title":"📰 CỘNG ĐỒNG",
"mobileCommunity.news":"📰 Tin hàng ngày",
"mobileCommunity.articles":"✍️ Thư viện bài viết",
"mobileCommunity.members":"👥 DS thành viên",
"mobileCommunity.finance":"💰 Tài chính",
"mobilePersonal.title":"👤 CÁ NHÂN",
"mobilePersonal.login":"🔐 Đăng nhập",
"mobilePersonal.register":"📝 Đăng ký",
"lichsu.back":"← Quay lại",
"lichsu.backList":"← Quay lại danh sách",
"lichsu.source":"Nguồn tư liệu:",
"lichsu.empty":"Chưa có dữ liệu lịch sử.",
"lichsu.alt":"Lịch sử Hiền Lương"

    },
    en:{
        "header.subtitle":"My Homeland",
        "marquee":"❤️ Welcome to the Hiền Lương Website • Preserving our homeland memories • Connecting Hiền Lương people around the country ❤️",
        "nav.home":"Home",
        "nav.menu":"Menu",
        "nav.community":"Community",
        "nav.hangkinh":"Blacksmith Guild",
        "nav.explore":"Explore",
        "nav.fund":"Village Fund",
        "nav.personal":"Personal",
"explore.title":"EXPLORE",
"explore.subtitle":"Hiền Lương Homeland",
"explore.intro":"Introduction",
"explore.history":"History",
"explore.famous":"Notable Figures",
"explore.tourism":"Tourist Attractions",
"explore.craft":"Local Crafts & Products",
"explore.landmark":"Historical Places",
"explore.clan":"Family Clans",
"explore.documents":"Documents",
"explore.notice":"Announcements",
"community.title":"CONNECT",
"community.subtitle":"Hiền Lương Community",
"community.news":"Daily News",
"community.articles":"Article Library",
"community.members":"Member Directory",
"community.finance":"Finance",
"personal.title":"ACCOUNT",
"personal.subtitle":"Personal Area",
"personal.login":"Log In",
"personal.register":"Register",
"hero.title":"Explore Our Homeland",
"hero.heading":"Heritage",
"hero.years":"500 Years",
"hero.heading2":"The Red Flame by the Bo River",
"hero.description":"Stories, memories, people, and cultural values preserved through every section.",
"culture.title":"HOMELAND",
"culture.heading":"History & Culture",
"culture.intro":"Introduction",
"culture.introDesc":"Discover Hiền Lương, our homeland.",
"culture.history":"History & Worship",
"culture.historyDesc":"Milestones and memories of our homeland.",
"culture.famous":"Notable Figures",
"culture.famousDesc":"Outstanding people from our homeland.",
"culture.tourism":"Tourist Attractions",
"culture.tourismDesc":"Scenic places and destinations of our homeland.",
"culture.craft":"Local Crafts & Products",
"culture.craftDesc":"Local products and traditional village crafts.",
"culture.landmark":"Historical Places",
"culture.landmarkDesc":"Places connected with the history of our homeland.",
"culture.clan":"Family Clans",
"culture.clanDesc":"Family clans and genealogies of our homeland.",
"culture.documents":"Documents",
"culture.documentsDesc":"Valuable documents about Hiền Lương.",
"culture.notice":"Announcements",
"culture.noticeDesc":"Announcements from the Hiền Lương community.",
"communityCards.title":"COMMUNITY",
"communityCards.heading":"Connecting Hiền Lương People",
"communityCards.news":"Daily News",
"communityCards.newsDesc":"Stories and news from our homeland.",
"communityCards.articles":"Article Library",
"communityCards.articlesDesc":"A place to share personal stories.",
"communityCards.members":"Member Directory",
"communityCards.membersDesc":"The community of Hiền Lương people.",
"communityCards.finance":"Finance",
"communityCards.financeDesc":"Financial information of the community.",
"hangkinh.title":"BLACKSMITH GUILD",
"hangkinh.heading":"Connecting Fellow Villagers & Craft Guilds",
"hangkinh.motto":"18 Hàng Kỉnh: \"Ly Hương Bất Ly Tổ\"",
"hangkinh.intro":"A unique craft-guild organization of Hiền Lương blacksmiths, connecting guild branches from Đông Hà, Quảng Trị, Câu Nhi, Huế, Đà Nẵng and Ho Chi Minh City to overseas Vietnamese communities.",
"hangkinh.listTitle":"Historical Directory of the 18 Hàng Kỉnh Branches (Dr. Bùi Thị Tân, 1996):",
"hangkinh.loading":"Loading Hàng Kỉnh directory...",
"tientho.label":"HONORING OUR FOUNDING ANCESTORS",
"tientho.title":"List of Founding Ancestors",
"tientho.description":"The ancestors who laid the foundation for the founding of Hoa Lang Village in 1445.",
"tientho.loading":"⏳ Loading the list of Founding Ancestors...",
"thuocphim.label":"HOMELAND MEMORIES",
"thuocphim.title":"Precious Films of Hiền Lương Village",
"thuocphim.description":"Images and films preserving the memories, people, and heartfelt stories of Hiền Lương homeland.",
"thuocphim.screenTitle":"HIỀN LƯƠNG FILMS",
"thuocphim.screenHint":"Select a film below",
"thuocphim.loading":"⏳ Loading the film list...",
"tuhao.label":"HOMELAND PRIDE",
"tuhao.title":"10+ Streets in Huế Honoring Hiền Lương's Blacksmith Village",
"tuhao.street1":"Hoàng Văn Lịch Street",
"tuhao.desc1":"Bãi Dâu Port, Huế • First mechanical engineer to build a steamship",
"tuhao.street2":"Nguyễn Lương Nhàn Street",
"tuhao.desc2":"Connecting TL11C and TL9 (Phong Thái) • Bình Thắng Nam, Provincial Administrator",
"tuhao.street3":"Trương Như Cương Street",
"tuhao.desc3":"New Huế urban area • Hiền Lương Marquis, Senior Court Official",
"tuhao.street4":"Trần Đình Bá Street",
"tuhao.desc4":"Central Huế • Doctoral laureate, Minister of Justice and War",
"tuhao.street5":"Trần Văn Đắc Street",
"tuhao.desc5":"Phong Thái Ward • Seventh-rank official of the Nguyễn Dynasty's Gun Foundry",
"tuhao.street6":"Hoa Lang & Triều Dương Streets",
"tuhao.desc6":"Phong Thái Ward • Honoring the village's founding name in 1445 and its six guilds",
"disan.label":"HOMELAND HERITAGE",
"disan.title":"Traditional Craft Heritage",
"disan.subtitle":"Three Sources Sustaining Life Along the Bo River",
"disan.description":"The generations-old blacksmithing tradition, combined with the fragrance of pure peanut oil and the purple hues of riverside mulberry fields, creates a rich and distinctive cultural economy of our homeland.",
"disan.ren.title":"A Century of Blacksmithing Fire",
"disan.ren.description":"The traditional \"burning knife, burning machete\" technique places quality steel between two bars of mild iron, then tempers it in salt water and buffalo-horn powder, producing blades that can strike stone without chipping. The craft also contributed weapons to the royal court and the construction of three steamships: Yên Phi, Vân Phi, and Vũ Phi.",
"disan.ren.quote":"\"Lưỡng diệt hoàng sa, ông tướng đại ca tay cầm thiết thù...\"",
"disan.dauphung.title":"Traditional Hand-Pressed Peanut Oil",
"disan.dauphung.description":"Locally grown sẻ peanuts are carefully selected, ground, steamed, and pressed using a traditional wooden press. Every drop is golden, richly fragrant, and 100% pure, with no additives.",
"disan.dauphung.quote":"A cherished flavor on the family tables of Huế.",
"disan.dau.title":"Riverside Mulberry Fields",
"disan.dau.description":"Hiền Lương mulberries are grown purely for their ripe fruit, soaked with rock sugar to refresh people on hot summer afternoons. There is no silk-rearing or silk-weaving tradition here. A simple and elegant gift from the countryside.",
"disan.dau.quote":"A rustic herbal drink deeply connected to childhood memories.",
"guibai.label":"HIỀN LƯƠNG EDITORIAL BOARD",
"guibai.title":"Submit an Article or Heritage Item to the Editorial Board",
"guibai.description":"Share your stories, images, and valuable documents to help preserve the memories of Hiền Lương homeland.",
"guibai.author":"Author / Contributor Name",
"guibai.phone":"Phone Number / Zalo",
"guibai.branch":"Hàng Kỉnh Branch / Place of Residence",
"guibai.content":"Summary of the article or contributed material",
"guibai.submit":"Submit Information to the Editorial Board",
"footer.title":"HIỀN LƯƠNG BLACKSMITH VILLAGE",
"footer.about":"Preserving the intangible cultural heritage of the ancient capital of Huế. A place where the heritage of more than 500 years of metalworking craftsmanship comes together.",
"footer.contact":"Contact Information",
"footer.address":"Phong Hiền Commune, Phong Điền District, Thừa Thiên Huế Province",
"footer.hotline":"Hotline: 098x xxx xxx (Editorial Board)",
"footer.map":"Location on the Map",
"footer.distance":"About 25 km north of Huế city center.",
"footer.mapLink":"Open Google Maps Directions",
"footer.version":"Website Version 2.0.0",
"footer.written":"Written by: Trương Văn Thành",
"footer.admin":"Admin Login",
"footer.copyright":"© 2026 HIỀN LƯƠNG. All Rights Reserved.",
"mobile.home":"Home",
"mobile.category":"Categories",
"mobile.community":"Community",
"mobile.personal":"Personal",
"mobileCategory.title":"📚 CATEGORIES",
"mobileCategory.intro":"📘 Introduction",
"mobileCategory.history":"📜 History",
"mobileCategory.famous":"👤 Notable Figures",
"mobileCategory.tourism":"🏞 Tourist Attractions",
"mobileCategory.craft":"🍲 Local Crafts & Products",
"mobileCategory.landmark":"📍 Historical Places",
"mobileCategory.clan":"👪 Family Clans",
"mobileCategory.documents":"📚 Documents",
"mobileCategory.notice":"📢 Announcements",
"mobileCommunity.title":"📰 COMMUNITY",
"mobileCommunity.news":"📰 Daily News",
"mobileCommunity.articles":"✍️ Article Library",
"mobileCommunity.members":"👥 Member Directory",
"mobileCommunity.finance":"💰 Finance",
"mobilePersonal.title":"👤 PERSONAL",
"mobilePersonal.login":"🔐 Log In",
"mobilePersonal.register":"📝 Register",
"lichsu.back":"← Back",
"lichsu.backList":"← Back to list",
"lichsu.source":"Source:",
"lichsu.empty":"No historical data available.",
"lichsu.alt":"Hiền Lương History"

    }
};

export function getLanguage(){
    return "vi";
}

export function setLanguage(lang){
    return;
}

const currentLanguage=getLanguage();
document.documentElement.lang=currentLanguage;
document.documentElement.dataset.language=currentLanguage;

export function t(key){
    const lang=getLanguage();
    return LANGUAGES[lang]?.[key]||LANGUAGES.vi[key]||key;
}